name: kuungaa
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+2

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  material_design_icons_flutter: ^5.0.6595
  snippet_coder_utils: ^1.0.9
  font_awesome_flutter: ^9.2.0
  dropdown_below: ^1.0.2
  mime: ^1.0.1
  chewie: ^1.2.2
  http: ^0.13.4
  geolocator: ^7.4.0
  google_maps_flutter: ^2.2.0
  provider: ^6.0.3
  video_player: ^2.2.8
  share_plus: ^4.0.10
  intl: ^0.17.0
  flick_video_player: ^0.5.0
  visibility_detector: ^0.2.2
  flutter_colorpicker: ^1.0.3
  loading_overlay: ^0.3.0
  path: ^1.8.0
  shimmer: ^2.0.0
  extended_image: ^6.0.1
  flutter_launcher_icons: ^0.9.2
  external_path: ^1.0.1
  page_transition: "^2.0.4"
  video_thumbnail: ^0.4.3
  path_provider: ^2.0.6
  flutter_video_info: ^1.2.0
  flutter_share_me: ^1.2.0
  photo_manager: ^2.1.4
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.0
  firebase_database: ^8.2.0
  firebase_storage: ^10.2.4
  fluttertoast: ^8.0.8
  flutter_staggered_grid_view: ^0.4.0
  country_icons: ^2.0.2
  group_radio_button: ^1.2.0
  date_field: ^2.1.3
  flutter_reaction_button: ^2.0.0+1
  lazy_load_scrollview: ^1.3.0
  sdp_transform: ^0.3.2
  camera: ^0.9.4+14
  permission_handler: ^6.0.0
  websocket_manager: ^0.2.2
  firebase_messaging: ^11.2.12
  flutter_local_notifications: ^9.4.0
  shared_preferences: ^2.0.13
  image_picker: ^0.8.5
  firebase_dynamic_links: ^4.2.2
  image_downloader: ^0.31.0
  image: ^3.1.3
  flutter_image_compress: ^1.1.0
  anim_search_bar: ^2.0.2
  flutter_chat_bubble: ^2.0.0
  loading_animation_widget: ^1.2.0+2
  readmore: ^2.1.0
  marquee: ^2.2.3
  styled_text: ^5.1.0
  flutter_linkify: ^5.0.2
  url_launcher: ^6.1.5
  file_picker: ^5.0.1
  audioplayers: ^1.0.1
  flutter_sound: ^9.2.13
  inview_notifier_list: ^3.0.0
  flutter_contacts: ^1.1.5
  preload_page_view: ^0.1.6
  week_of_year: ^2.0.0
  soundpool: ^2.3.0
  web_socket_channel: ^2.2.0
  flutter_webrtc: ^0.9.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "images/login_logo_dark.png"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - images/
     #- images/logo.svg
     #- images/profile.jpg
     #- images/klogo.png
     #- images/kuungaaboxlogo.png
     #- images/video_thumbnail.png
     #- images/cover_bg.jpg
     #- images/reactions_angry.png
     #- images/reactions_haha.png
     #- images/reactions_like.png
     #- images/reactions_love.png
     #- images/reactions_sad.png
     #- images/reactions_wow.png
     - sounds/
     - mapstyles/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Signatra
      fonts:
        - asset: fonts/Signatra.ttf
    - family: San Fransisco
      fonts:
        - asset: fonts/SanFransiscoRegular.otf
    - family: Dosis Bold
      fonts:
        - asset: fonts/Dosis_Bold.ttf
    - family: Dosis ExtraBold
      fonts:
        - asset: fonts/Dosis_ExtraBold.ttf
    - family: Dosis ExtraLight
      fonts:
        - asset: fonts/Dosis_ExtraLight.ttf
    - family: Dosis Light
      fonts:
        - asset: fonts/Dosis_Light.ttf
    - family: Dosis Medium
      fonts:
        - asset: fonts/Dosis_Medium.ttf
    - family: Dosis Regular
      fonts:
        - asset: fonts/Dosis_Regular.ttf
    - family: Dosis SemiBold
      fonts:
        - asset: fonts/Dosis_SemiBold.ttf
    - family: Sen Regular
      fonts:
        - asset: fonts/Sen_Regular.ttf
    - family: icomoon
      fonts:
        - asset: fonts/icomoon.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
